{{- if .Values.notebook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fraud-detection.fullname" . }}-lakefs-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fraud-detection.labels" . | nindent 4 }}
    app.kubernetes.io/component: notebook
type: Opaque
stringData:
  accessKeyId: {{ .Values.lakefs.adminCredentials.accessKeyId | quote }}
  secretAccessKey: {{ .Values.lakefs.adminCredentials.secretAccessKey | quote }}
{{- end }}

