{{- if and .Values.openshift.enabled .Values.openshift.routes.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "lakefs.fullname" . }}
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  {{- if .Values.openshift.routes.tls }}
  tls:
    termination: {{ .Values.openshift.routes.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.routes.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "lakefs.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}

