apiVersion: v2
name: fraud-detection
description: Fraud Detection with LakeFS, MinIO, and PostgreSQL for data versioning and model registry
type: application
version: 1.2.0
appVersion: "1.2"
keywords:
  - lakefs
  - minio
  - postgresql
  - postgres
  - fraud-detection
  - data-versioning
  - model-registry
  - openshift
  - ai-ml
  - openshift-ai
home: https://github.com/rh-ai-quickstart/Fraud-Detection-data-versioning-with-lakeFS
maintainers:
  - name: Red Hat AI Quickstart Team
dependencies:
  - name: minio
    version: 0.5.2
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: minio.enabled

