{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name | default "postgres" }}
  namespace: {{ .Values.postgres.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name | default "postgres" }}
    {{- include "fraud-detection.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.port | default 5432 }}
      targetPort: postgres
      protocol: TCP
  selector:
    app: {{ .Values.postgres.name | default "postgres" }}
{{- end }}
