kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "lakefs.fullname" . }}
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.route.annotations | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "lakefs.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    termination: {{ .Values.route.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None