{{- if and .Values.mysql.enabled .Values.openshift.enabled }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.mysql.imageName | default "mysql" }}
  namespace: {{ .Values.mysql.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.mysql.imageName | default "mysql" }}
    {{- include "fraud-detection.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStreamTag
metadata:
  name: {{ .Values.mysql.imageName | default "mysql" }}:{{ .Values.mysql.imageTag | default "latest" }}
  namespace: {{ .Values.mysql.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.mysql.imageName | default "mysql" }}
    {{- include "fraud-detection.labels" . | nindent 4 }}
spec:
  tag:
    from:
      kind: DockerImage
      name: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
{{- end }}

