{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name | default "mysql" }}
  namespace: {{ .Values.mysql.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.mysql.name | default "mysql" }}
    {{- include "fraud-detection.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | default "1Gi" }}
  {{- if .Values.mysql.persistence.storageClassName }}
  storageClassName: {{ .Values.mysql.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}

