{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name | default "mysql" }}
  namespace: {{ .Values.mysql.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.mysql.name | default "mysql" }}
    {{- include "fraud-detection.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-name: {{ .Values.mysql.database | quote }}
  database-user: {{ .Values.mysql.user | quote }}
  database-password: {{ .Values.mysql.password | quote }}
  database-root-password: {{ .Values.mysql.rootPassword | quote }}
{{- end }}

