{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name | default "mysql" }}
  namespace: {{ .Values.mysql.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.mysql.name | default "mysql" }}
    {{- include "fraud-detection.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: {{ .Values.mysql.port | default 3306 }}
      targetPort: mysql
      protocol: TCP
  selector:
    app: {{ .Values.mysql.name | default "mysql" }}
    deployment: {{ .Values.mysql.name | default "mysql" }}
{{- end }}

